### ISSUE TITLE
Feature Request: Reduce steps for running

### ISSUE THREAD

**Issue by hasteur** [zhaofengli/reflinks#1]
Your tool is being used by the AfC project/process and appears to work well, however there is a problem. We click a link in our template which can take us over to your tool and then have to fill in the page name and click the link to get the result.  I have two desired options:

1. Allow a GET request to pre-populate the Page name box give us the option to click the "Fix Page" submit button
2. Take us to the result page of clicking the submit button from providing the page.

Thanks

**Comment by zhaofengli** [comment]
It's possible to get to the result page directly, just use `{{fullurl:toollabs:fengtools/reflinks/result.php|page={{FULLPAGENAMEE}}&defaults=y}}` as on [Template:Cleanup-bare URLs](https://en.wikipedia.org/w/index.php?title=Template:Cleanup-bare_URLs&action=edit). The tool accepts the same set of parameters in POST and GET, and you can mix both together.

**Comment by zhaofengli** [comment]
Looks like it's [done](https://en.wikipedia.org/w/index.php?title=Template:AFC_submission/tools&diff=prev&oldid=643009481). :+1:
