### ISSUE TITLE
Doesn't encode page names

### ISSUE THREAD

**Issue by Technical-13** [zhaofengli/reflinks#2]
I was attempting to run the script on http://enwp.org/Dungeons_%26_Dragons_Online and was curious to why I kept getting sent to http://enwp.org/Dungeons to post the results when I realized the link to the page was `https://en.wikipedia.org/w/index.php?title=Dungeons_&_Dragons_Online&action=submit` and it was breaking on the `&` in the middle of the title.  https://github.com/zhaofengli/reflinks/blob/fd6be503ab4b126bec558d8288cc9d6a63777956/style/templates/result.html#L13 shows that it is sending `?title={{ pagename }}&action=submit` back to the page.  I'm not familiar enough with your setup to know if there is a `{{ url_encoded_pagename }}` of some kind or where those variables are coming from, but that is what is needed to correct this problem.

**Comment by zhaofengli** [comment]
Fixed. Thanks for reporting! :-1:
